[tool.poetry]
name = "gdatalog"
version = "0.0.5"
description = "Genereative Datalog with stable negation"
authors = ["Mario Alviano <mario.alviano@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
typer = "^0.9.0"
rich = "^13.0.1"
typeguard = "^4.1.5"
valid8 = "^5.1.2"
#scipy = "^1.10.0"  # scipy is not compatible with python3.10; temporary fix: $ pip install scipy
pytest = "^7.2.0"
dumbo-asp = "^0.0.58"
distlib = "^0.3.6"

[tool.poetry.dev-dependencies]
coverage = "^7.0.4"
pytest = "^7.2.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
